main: lowbrain.items.main.LowbrainItems
name: LowbrainItems
version: 0.0.1
author: Lowbrain
depend: [LowbrainLibrary]
softdepend: [LowbrainEconomy]
description: Create custom items
permission:
 lb.items.give-self:
  description: give custom item to yourself
  default: op
 lb.items.give-others:
  description: give custom item to other players
  default: op
 lb.items.list:
  description: list all items
  default: op
commands:
 lbitems:
  usage: |
              Use /help lbitems [subcommand] for more information
              /lbitems give <item name> <amount> - give a certain item to yourself
              /lbitems give <player> <item name> <amount> - give a certain item to a other player
              /lbitems list - list all items